@startuml
class Usuario {
    - String nome
    - String nomeUsuario
    - Date dataNascimento
    + int getIdade()
}

class InformacaoPessoal {
    - String email
    - String telefone
    - String senha
}

class Postagem {
}

Usuario "1"-->"1" InformacaoPessoal
Usuario "1"--> "0..*" Postagem

@enduml